[project]
name = "nrwpe-experiment"
version = "0.1.0"
requires-python = ">=3.10,<3.12"
dependencies = [
    "numpy",
    "loguru",
    "psutil",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.backends._legacy:_Backend"
